### ISSUE TITLE
Underflow on numStateConstraints

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/ndcurves#27]
I am currently working with the optimisation examples and get an underflow on `numStateConstraints` (I assume it sets a negative value).

**Comment by stonneau** [comment]
Hi, 
this probably happens because you have too many constraints given the degree of your curve. An exception should be raised in such case. Thanks for raising the issue.

However if you have a case where this happens it would be helpful because this error is supposed to be caught and an exception raised

**Comment by wxmerkt** [comment]
Thank you. I now think this is more closely related to #28 since there is an `assert` that should have caught this.

**Comment by pFernbach** [comment]
Is this issue solved by https://github.com/loco-3d/curves/pull/29 ?

**Comment by wxmerkt** [comment]
Potentially - I haven't tested recently but think it should be - will close the issue.
